### ISSUE TITLE
CPU Usage

### ISSUE THREAD

**Issue by 6ix-Raptors** [andreivdev/coolm1#5]
The new version of the app is really nice and it works well. I really like that its in the menu bar. The problem is its using [5.4](<img width="1170" alt="Screen Shot 2021-06-11 at 12 02 20 PM" src="https://user-images.githubusercontent.com/77996753/121715439-e3cd4b80-caac-11eb-8ff6-b8d64501bbd1.png">) % of my CPU, and comparing that to Firefox which is only using 3.2 its kinda concerning me. I use  gao-sun /
eul for CPU and Ram usage in my menu bar and that only uses 1.2%. Im wondering if your able to optimize it or if your able to intergreate something similar to eul that will include CPU, Ram, etc along with being able to check M1 temperatures. If you could I know thousands of people with m1 macs will thank you, especially me. Thanks for your time!

**Comment by andreivdev** [comment]
If you want the menu bar temperature text to work, there is no way around it.

The entire app has to load and keep running in memory.

This is a limitation of electron.
